export default {
  FETCH_DOGS_REQUEST: 'FETCH_DOGS_REQUEST',
  FETCH_DOGS_SUCCESS: 'FETCH_DOGS_SUCCESS',
  FETCH_DOGS_FAILURE: 'FETCH_DOGS_FAILURE',
  FETCH_USER_PHOTOS_REQUEST: 'FETCH_USER_PHOTOS_REQUEST',
  FETCH_USER_PHOTOS_SUCCESS: 'FETCH_USER_PHOTOS_SUCCESS',
  FETCH_USER_PHOTOS_FAILURE: 'FETCH_USER_PHOTOS_FAILURE',
  CLEAR_USER_DATA: 'CLEAR_USER_DATA',
};

